#!/bin/sh

set -eu

lb config noauto \
    --architectures amd64 \
    --distribution trixie \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-chroot-security "http://security.debian.org/debian-security/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --mirror-binary-security "http://security.debian.org/debian-security/" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --apt-recommends false \
    --debian-installer false \
    --firmware-binary true \
    --firmware-chroot true \
    --memtest none \
    --iso-application "NM-OS" \
    --iso-publisher "https://github.com/Krypera/NM-OS" \
    --iso-volume "NM-OS ALPHA" \
    --linux-packages none \
    --bootappend-live "boot=live components noautologin hostname=nmos username=nmos quiet splash console=tty1 console=ttyS0,115200n8 nmos.mode=strict" \
    "${@}"
