branding: nmos
prompt-install: false
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true
window-expanding: true
fullscreen: true
default-locale: en_US
module-search:
  - /usr/lib/x86_64-linux-gnu/calamares/modules
modules-search:
  - /etc/calamares/modules
